plugin:
  autoStopEnabled: true # whether to stop the server if all players left
  autoStopTimeout: 300 # 5 minutes
  startTimeout: true # whether to start the autoStopTimeout on server start
  startTimeoutDelay: 60 # delay the timeout on server start
standalone:
  serverPort: 25565 # should be equal to the server port

  protocolVersion: 1 # if equal to your MC client version, it will show player count (below)
  versionName: "Stopped" # if protocol version differs from the client, this text will be shown
  playersOnline: 0
  playersMax: 0

  motd: "The server is stopped, join to start."
  startingText: "Hi $USERNAME, the server is starting..."
  disconnectText: "You are not whitelisted to start this server."

  whitelistEnabled: true # allow only certain players to start the server
  whitelistUseServer: true # whether to use the server whitelist (plugins/../whitelist.json)
  whitelist: []
